const pandaemonium = [
  {
    type: "category",
    label: "P1S - Erichthonios",
    items: [
      "savage/pandaemonium/p1s/p1s"
    ]
  },
  {
    type: "category",
    label: "P2S - Hippokampos",
    items: [
      "savage/pandaemonium/p2s/p2s"
    ]
  },
  {
    type: "category",
    label: "P3S - Phoinix",
    items: [
      "savage/pandaemonium/p3s/p3s"
    ]
  },
  {
    type: "category",
    label: "P4S - Hesperos",
    items: [
      "savage/pandaemonium/p4s/p4s"
    ]
  },
  {
    type: "category",
    label: "P5S - Proto-Carbuncle",
    items: [
      "savage/pandaemonium/p5s/p5s"
    ]
  },
  {
    type: "category",
    label: "P6S - Hegemone",
    items: [
      "savage/pandaemonium/p6s/p6s"
    ]
  },
  {
    type: "category",
    label: "P7S - Agdistis",
    items: [
      "savage/pandaemonium/p7s/p7s"
    ]
  },
  {
    type: "category",
    label: "P8S - Hephaistos",
    items: [
      "savage/pandaemonium/p8s/p8s"
    ]
  },
  {
    type: "category",
    label: "P9S - Kokytos",
    items: [
      "savage/pandaemonium/p9s/p9s"
    ]
  },
  {
    type: "category",
    label: "P10S - Pandaemonium",
    items: [
      "savage/pandaemonium/p10s/p10s"
    ]
  },
  {
    type: "category",
    label: "P11S - Themis",
    items: [
      "savage/pandaemonium/p11s/p11s"
    ]
  },
  {
    type: "category",
    label: "P12S - Athena",
    items: [
      "savage/pandaemonium/p12s/p12s_p1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_2",
      "savage/pandaemonium/p12s/p12s_p1_superchain_1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_3",
      "savage/pandaemonium/p12s/p12s_p1_palladion",
      "savage/pandaemonium/p12s/p12s_p1_superchain_2a",
      "savage/pandaemonium/p12s/p12s_p1_superchain_2b",
      "savage/pandaemonium/p12s/p12s_p2",
      "savage/pandaemonium/p12s/p12s_p2_gaiaochos_1",
      "savage/pandaemonium/p12s/p12s_p2_classical_1",
      "savage/pandaemonium/p12s/p12s_p2_caloric_1",
      "savage/pandaemonium/p12s/p12s_p2_pangenesis",
      "savage/pandaemonium/p12s/p12s_p2_classical_2",
      "savage/pandaemonium/p12s/p12s_p2_caloric_2",
      "savage/pandaemonium/p12s/p12s_p2_gaiaochos_2"
    ]
  }
];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/
  mySideBar: [
    {type: 'doc', id: 'Home', label: 'Home'},
    {type: 'doc', id: 'About this website', label: 'About this website'},
    {type: 'doc', id: 'Cultural differences between DCs', label: 'Cultural differences between DCs'},
    {
      type: 'category',
      label: '=w=',
      items: [
        {type: "doc", id: "=w=/dsr_uptime_exaflare", label: "DSR Uptime Exaflare"}
      ]
    },
    {
      type: 'category',
      label: 'Savage',
      items: [
        {type: "category", label: "Pandaemonium", items: pandaemonium}
      ]
    },
    {
      type: 'category',
      label: 'Criterion',
      items: [
        {
          type: "category", label: "Mount Rokkon", items: [
            {type: "doc", id: "criterion/mount_rokkon/mount_rokkon", label: "Intro"}
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
