const arcadion = [
  {
    type: "doc",
    id: "savage/arcadion/index",
    label: "Index"
  },
  {
    type: "category",
    label: "M1S - Black Cat",
    items: [
      "savage/arcadion/m1s/m1s",
      "savage/arcadion/m1s/m1s_nine_lives_1",
      "savage/arcadion/m1s/m1s_mouser_1",
      "savage/arcadion/m1s/m1s_nine_lives_2",
      "savage/arcadion/m1s/m1s_mouser_2",
      "savage/arcadion/m1s/m1s_raining_cats"
    ]
  },
  {
    type: "category",
    label: "M2S - Honey B. Lovely",
    items: [
      "savage/arcadion/m2s/m2s",
      "savage/arcadion/m2s/m2s_beat_1",
      "savage/arcadion/m2s/m2s_alarm_pheromones_1",
      "savage/arcadion/m2s/m2s_beat_2",
      "savage/arcadion/m2s/m2s_alarm_pheromones_2",
      "savage/arcadion/m2s/m2s_beat_3",
      "savage/arcadion/m2s/m2s_rotten_heart",
    ]
  },
  {
    type: "category",
    label: "M3S - Brute Bomber",
    items: [
      "savage/arcadion/m3s/m3s",
      "savage/arcadion/m3s/m3s_doping_1",
      "savage/arcadion/m3s/m3s_tag_team_1",
      "savage/arcadion/m3s/m3s_final_fusedown",
      "savage/arcadion/m3s/m3s_fusefield",
      "savage/arcadion/m3s/m3s_doping_2",
      "savage/arcadion/m3s/m3s_tag_team_2",
      "savage/arcadion/m3s/m3s_fuse_or_foe"
    ]
  },
  {
    type: "category",
    label: "M4S - Wicked Thunder",
    items: [
      "savage/arcadion/m4s/m4s",
      "savage/arcadion/m4s/m4s_bewitching_flight",
      "savage/arcadion/m4s/m4s_electrope_edge_1",
      "savage/arcadion/m4s/m4s_electrope_edge_2",
      "savage/arcadion/m4s/m4s_electron_stream",
      "savage/arcadion/m4s/m4s_electrope_transplant",
      "savage/arcadion/m4s/m4s_cross_tail_switch",
      "savage/arcadion/m4s/m4s_twilight_sabbath",
      "savage/arcadion/m4s/m4s_midnight_sabbath",
      "savage/arcadion/m4s/m4s_chain_lightning",
      "savage/arcadion/m4s/m4s_sunrise_sabbath"
    ]
  },
]

const pandaemonium = [
  {
    type: "doc",
    id: "savage/pandaemonium/index",
    label: "Index"
  },
  // {
  //   type: "category",
  //   label: "P1S - Erichthonios",
  //   items: [
  //     "savage/pandaemonium/p1s/p1s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P2S - Hippokampos",
  //   items: [
  //     "savage/pandaemonium/p2s/p2s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P3S - Phoinix",
  //   items: [
  //     "savage/pandaemonium/p3s/p3s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P4S - Hesperos",
  //   items: [
  //     "savage/pandaemonium/p4s/p4s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P5S - Proto-Carbuncle",
  //   items: [
  //     "savage/pandaemonium/p5s/p5s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P6S - Hegemone",
  //   items: [
  //     "savage/pandaemonium/p6s/p6s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P7S - Agdistis",
  //   items: [
  //     "savage/pandaemonium/p7s/p7s"
  //   ]
  // },
  // {
  //   type: "category",
  //   label: "P8S - Hephaistos",
  //   items: [
  //     "savage/pandaemonium/p8s/p8s"
  //   ]
  // },
  {
    type: "category",
    label: "P9S - Kokytos",
    items: [
      "savage/pandaemonium/p9s/p9s"
    ]
  },
  {
    type: "category",
    label: "P10S - Pandaemonium",
    items: [
      "savage/pandaemonium/p10s/p10s"
    ]
  },
  {
    type: "category",
    label: "P11S - Themis",
    items: [
      "savage/pandaemonium/p11s/p11s"
    ]
  },
  {
    type: "category",
    label: "P12S - Athena",
    items: [
      "savage/pandaemonium/p12s/p12s_p1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_2",
      "savage/pandaemonium/p12s/p12s_p1_superchain_1",
      "savage/pandaemonium/p12s/p12s_p1_paradeigma_3",
      "savage/pandaemonium/p12s/p12s_p1_palladion",
      "savage/pandaemonium/p12s/p12s_p1_superchain_2a",
      "savage/pandaemonium/p12s/p12s_p1_superchain_2b",
      "savage/pandaemonium/p12s/p12s_p2",
      "savage/pandaemonium/p12s/p12s_p2_gaiaochos_1",
      "savage/pandaemonium/p12s/p12s_p2_classical_1",
      "savage/pandaemonium/p12s/p12s_p2_caloric_1",
      "savage/pandaemonium/p12s/p12s_p2_pangenesis",
      "savage/pandaemonium/p12s/p12s_p2_classical_2",
      "savage/pandaemonium/p12s/p12s_p2_caloric_2",
      "savage/pandaemonium/p12s/p12s_p2_gaiaochos_2"
    ]
  }
];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/
  mySideBar: [
    {type: 'doc', id: 'Home', label: 'Home'},
    {type: 'doc', id: 'About this website', label: 'About this website'},
    {type: 'doc', id: 'Cultural differences between DCs', label: 'Cultural differences between DCs'},
    {
      type: 'category',
      label: '=w=',
      items: [
        {type: "doc", id: "=w=/dsr_uptime_exaflare", label: "DSR Uptime Exaflare"}
      ]
    },
    {
      type: 'category',
      label: 'Savage',
      items: [
        {type: "category", label: "Arcadion", items: arcadion},
        {type: "category", label: "Pandaemonium", items: pandaemonium}
      ]
    },
    {
      type: 'category',
      label: 'Criterion',
      items: [
        {
          type: "category", label: "Mount Rokkon", items: [
            {type: "doc", id: "criterion/mount_rokkon/mount_rokkon", label: "Intro"}
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
